create table bank_accounts(
    id      integer generated by default as identity,
    balance numeric(19, 2),
    number  varchar(255),
    primary key (id)
);

create table clients(
    id              integer generated by default as identity,
    email           varchar(255),
    firstname       varchar(255),
    lastname        varchar(255),
    username        varchar(255),
    bank_account_id integer,
    primary key (id),
    constraint clients_fk foreign key (bank_account_id)
        references bank_accounts (id)
)
