spring:
  datasource:
    url: jdbc:postgresql://payment-service-db:5435/payment_db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://keycloak:8181/realms/order-processing-system-realm'

  zipkin:
    base-url: http://zipkin:9411

  kafka:
    bootstrap-servers: 'kafka:29092'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka