spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: 'http://keycloak:8181/realms/master'

      resourceserver:
        jwt:
          issuer-uri: 'http://keycloak:8181/realms/order-processing-system-realm'

  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka